/*
===============================================================================
MAGNITUDE ANALYSIS
===============================================================================
Purpose: 
    - To analyze the distribution of business metrics across different dimensions.
    - To identify which countries, genders, or categories contribute most.
    - To understand the volume of data in various segments.
*/

-- 1. Customer Magnitude by Geography
-------------------------------------------------------------------------------
-- Find the total number of customers in each country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- 2. Customer Magnitude by Gender
-------------------------------------------------------------------------------
-- Find the total number of customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- 3. Product Magnitude by Category
-------------------------------------------------------------------------------
-- Find the total number of products within each category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- 4. Cost & Revenue Magnitude by Category
-------------------------------------------------------------------------------
-- What is the average cost for products in each category?
SELECT
    category,
    AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the total revenue generated for each category? (Fact + Dim Join)
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- 5. Sales Magnitude by Customer & Geography
-------------------------------------------------------------------------------
-- Total revenue generated by each customer (Top contributors)
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Distribution of items sold across countries
SELECT 
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
